"""Bounded, auditable consensus across application-supplied AI providers."""

from .consensus import (
    AgreementLevel,
    CallableProvider,
    CompletionCallable,
    ConsensusConfig,
    ConsensusEngine,
    ConsensusResult,
    Provider,
    ProviderOutcome,
    ProviderResponse,
    ProviderStatus,
)
from .evaluation import (
    ComparisonPolicy,
    ConsensusReachedScorer,
    ContainsScorer,
    EvaluationCase,
    EvaluationCaseResult,
    EvaluationPolicy,
    EvaluationReport,
    EvaluationRunConfig,
    EvaluationRunner,
    EvaluationScore,
    EvaluationSummary,
    ExactMatchScorer,
    GateViolation,
    ReplaySuite,
    ReportComparison,
    Scorer,
    ScoreStatus,
    compare_reports,
    load_evaluation_report,
    load_replay_suite,
)
from .observability import AttributeValue, ConsensusEvent, ConsensusObserver
from .usage import JsonlUsageStore, UsageRecord, UsageStatistics, UsageStore

__version__ = "0.2.0"

__all__ = [
    "AgreementLevel",
    "AttributeValue",
    "CallableProvider",
    "ComparisonPolicy",
    "CompletionCallable",
    "ConsensusConfig",
    "ConsensusEngine",
    "ConsensusEvent",
    "ConsensusObserver",
    "ConsensusReachedScorer",
    "ConsensusResult",
    "ContainsScorer",
    "EvaluationCase",
    "EvaluationCaseResult",
    "EvaluationPolicy",
    "EvaluationReport",
    "EvaluationRunConfig",
    "EvaluationRunner",
    "EvaluationScore",
    "EvaluationSummary",
    "ExactMatchScorer",
    "GateViolation",
    "JsonlUsageStore",
    "Provider",
    "ProviderOutcome",
    "ProviderResponse",
    "ProviderStatus",
    "ReplaySuite",
    "ReportComparison",
    "ScoreStatus",
    "Scorer",
    "UsageRecord",
    "UsageStatistics",
    "UsageStore",
    "__version__",
    "compare_reports",
    "load_evaluation_report",
    "load_replay_suite",
]
